### ISSUE TITLE
Mark as abandoned?

### ISSUE THREAD

**Issue by Nyholm** [php-http/helper#3]
As far as I can see, this library is not used by any of the php-http libraries. Is this something we still want to have?

**Comment by sagikazarmark** [comment]
The content will be moved to php-http/message after some refactoring.

**Comment by sagikazarmark** [comment]
As mentioned in the readme :wink:

**Comment by Nyholm** [comment]
Sorry, I did not see that in the readme. I still don't... Anyhow, it should be marked as Abandoned in packagist.
